### PR TITLE
make: link with Windows specific GL and GLU libraries

### PR DESCRIPTION
**Pull request by Biswa96**

### CODE REVIEW

**Comment by angelog0** [comment]
As results [here](https://github.com/msys2/MINGW-packages/issues/6693) the mos elegant fix would be to add the symlinks in `mingw-w64-x86_64-crt-git` package in MSYS2. Anyway I already adopted my fix...

**Comment by interkosmos** [comment]
As if statements are not a POSIX make standard, the README has been updated on how to override the `LIBGL` and `LIBGLU` parameters instead.

**Comment by Biswa96** [comment]
Alright. As you wish. Thank you ❤️

**Pull request closed without merging**
